## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('aodv-mobility',
                                 ['wifi', 'internet', 'aodv', 'internet-apps', 'netanim'])
    obj.source = 'aodv-mobility.cc'
